kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/schijioke-uche/shoprite-mobile-app.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: wakefern-mobile-proxy-app-v1
  #namespace: wkfn
  labels:
    app: wakefern-mobile-proxy-app-v1
    app.kubernetes.io/component: wakefern-mobile-proxy-app-v1
    app.kubernetes.io/instance: wakefern-mobile-proxy-app-v1
    app.kubernetes.io/part-of: wakefern-mobile-proxy-app-v1
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'wakefern-mobile-proxy-app-v1:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/schijioke-uche/shoprite-mobile-app.git'
      ref: master
    contextDir: /
    sourceSecret:
      name: git-vcs-prvate-access
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: wakefern-mobile-proxy-app-v1-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: wakefern-mobile-proxy-app-v1-github-webhook-secret
  runPolicy: Serial