apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: wkfn-spring-app-post-stage
spec:
  serviceAccountName: pipeline
  triggers:
    - name: wkfn-spring-app-post-stage
      template:
        ref: wkfn-spring-app-post-stage
