apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-wkfn-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: wkfn/environments/prod/wkfn-app/
    repoURL: https://github.com/mf-gitops/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
