kind: Secret
apiVersion: v1
metadata:
  name: wakefern-mobile-proxy-app-v1-secret
  #namespace: wkfn
type: Opaque
stringData:
  MYSQL_USER: "<PROVIDE>"
  MYSQL_PASSWORD: "<PROVIDE>"
  DATABASE_SERVICE_HOST: "<PROVIDE>"
  MYSQL_DATABASE: "<PROVIDE>"
  POSTGRESQL_USER: "<PROVIDE IF USING>"
  POSTGRESQL_PASSWORD: "<PROVIDE IF USING>"
  POSTGRESQL_SERVICE_HOST: "<PROVIDE IF USING>"
  POSTGRESQL_DATABASE: "<PROVIDE IF USING>"  