apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-wkfn-cluster-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "265"
  labels:
    gitops.tier.group: cntk
spec:
  ca:
    secretName: wkfn-self-signed-ca-cert
